name: e_commerce_app_project
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^4.2.2
  shared_preferences: 2.2.0
  google_fonts: 6.0.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  carousel_slider: ^5.0.0
  floating_bottom_navigation_bar: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/icon/
